version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tenderease-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tenderease-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: tenderease-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tenderease.lk
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - tenderease-network

  evaluation-service:
    build:
      context: ./backend/evaluation-service
      dockerfile: Dockerfile
    container_name: evaluation-service
    ports:
      - "8100:8100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tenderease_evaluation_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - tenderease-network

  committee-frontend:
    build:
      context: ./committee-frontend
    container_name: committee-frontend
    ports:
      - "8095:8095"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://evaluation-service:8100
    depends_on:
      - evaluation-service
    networks:
      - tenderease-network

networks:
  tenderease-network:
    driver: bridge

volumes:
  postgres_data:
