spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        
        - id: tender-service
          uri: lb://tender-service
          predicates:
            - Path=/api/tenders/**
          filters:
            - StripPrefix=1

        - id: officer-dashboard-service
          uri: lb://officer-dashboard-service
          predicates:
            - Path=/api/officer/**
        
        # Add more routes for other services
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/tenderease}

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka/}
