spring:
  config:
    import: "optional:file:../.env[.properties]"
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: user-service-vendors
          uri: lb://user-service
          predicates:
            - Path=/api/v1/vendors/**

        - id: tender-service
          uri: lb://tender-service
          predicates:
            - Path=/api/tenders/**
        - id: cao-tenders
          uri: lb://tender-service
          predicates:
            - Path=/api/cao/tenders/**
        
        - id: cao-users
          uri: lb://user-service
          predicates:
            - Path=/api/cao/officers/**, /api/cao/registrations/**

        - id: cao-kpi
          uri: lb://reporting-service
          predicates:
            - Path=/api/cao/kpi/**

        - id: cao-notifications
          uri: lb://notification-service
          predicates:
            - Path=/api/cao/notifications/**

        - id: cao-audit
          uri: lb://workflow-service
          predicates:
            - Path=/api/cao/audit-logs/**
        
        # Add more routes for other services
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://158.178.227.145:8080/realms/tenderease}

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
