ALTER TABLE dashboard_kpi ADD COLUMN sme_participation DOUBLE PRECISION DEFAULT 0;
ALTER TABLE dashboard_kpi ADD COLUMN awarded_tenders BIGINT DEFAULT 0;
ALTER TABLE dashboard_kpi ADD COLUMN average_cycle_time DOUBLE PRECISION DEFAULT 0;
ALTER TABLE dashboard_kpi ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
