package lk.tenderease.tender.enums;

public enum TimelineEventType {
    CREATED,
    SUBMITTED,
    APPROVED,
    REJECTED,
    PUBLISHED,
    OPENED,
    EVALUATION_STARTED,
    AWARDED,
    NO_BID,
    CLOSED,
    CANCELLED,
    AMENDED,
    REPORT_GENERATED,
    EVALUATED,
    SESSION_UNLOCKED,
    COMMITTEE_CHECKED_IN,
    BID_SUBMITTED,
    COMPLIANCE_MARKED,
    SCORES_FINALIZED
}